version: '3'

volumes:
  snap:

services:
  redis:
    image: redis
    restart: unless-stopped
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - "/srv/nimopidy/postgres:/var/lib/postgresql/data"
    env_file:
      - .env
  daphne:
    build: .
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - redis
      - postgres
    command: daphne -b 0.0.0.0 -p 8000 nimopidy.asgi:channel_layer
    env_file:
      - .env
  worker:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - snapserver
    command: ./manage.py runworker
    volumes:
      - "/srv/nimopidy/nimopidy:/srv/nimopidy"
    env_file:
      - .env
  migrate:
    build: .
    depends_on:
      - postgres
    command: ./manage.py migrate
    volumes:
      - "/srv/nimopidy/nimopidy:/srv/nimopidy"
    env_file:
      - .env
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "7000:8000"
    volumes:
      - "/srv/nimopidy:/srv/nimopidy"
      - "./conf/nginx:/etc/nginx/conf.d"
    links:
      - daphne
    env_file:
      - .env
  mopidy:
    build:
      context: .
      dockerfile: Dockerfile.mopidy
    restart: unless-stopped
    ports:
      - "6600:6600"
      - "6680:6680"
    depends_on:
      - snapserver
      - worker
    volumes:
      - "./conf/mopidy_global:/etc/mopidy"
      - "./conf/mopidy_local:/root/.config/mopidy"
      - "snap:/snap"
  snapserver:
    build:
      context: .
      dockerfile: Dockerfile.snapserver
    restart: unless-stopped
    ports:
      - "1705:1705"
      - "1704:1704"
    volumes:
      - "snap:/snap"
  playlists:
    build: .
    command: ./manage.py playlists
    depends_on:
      - redis
      - postgres
      - daphne
    volumes:
      - "/srv/nimopidy/nimopidy/:/srv/nimopidy"
    env_file:
      - .env
  play:
    build: .
    command: ./manage.py start
    depends_on:
      - redis
      - postgres
      - daphne
    env_file:
      - .env
