version: '3'

volumes:
  snap:

services:
  redis:
    image: redis
  postgres:
    image: postgres
    volumes:
      - "/srv/nimopidy/postgres:/var/lib/postgresql/data"
    env_file:
      - .env
  daphne:
    build: .
    expose:
      - "8000"
    depends_on:
      - redis
      - postgres
    command: daphne -b 0.0.0.0 -p 8000 nimopidy.asgi:channel_layer
    env_file:
      - .env
    volumes:
      - "./nimopidy:/app/nimopidy"
      - "./musicapp:/app/musicapp"
  worker:
    build: .
    depends_on:
      - redis
      - postgres
      - snapserver
    command: bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && ./manage.py runworker"
    volumes:
      - "/srv/nimopidy:/srv/nimopidy"
      - "./nimopidy:/app/nimopidy"
      - "./musicapp:/app/musicapp"
      - "./build:/app/build"
    env_file:
      - .env
  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - "/srv/nimopidy:/srv/nimopidy"
      - "./conf/nginx:/etc/nginx/conf.d"
    links:
      - daphne
    env_file:
      - .env
  mopidy:
    build:
      context: .
      dockerfile: Dockerfile.mopidy
    ports:
      - "6600:6600"
      - "6680:6680"
    depends_on:
      - snapserver
      - worker
    volumes:
      - "./conf/mopidy_global:/etc/mopidy"
      - "./conf/mopidy_local:/root/.config/mopidy"
      - "snap:/snap"
  snapserver:
    build:
      context: .
      dockerfile: Dockerfile.snapserver
    ports:
      - "1705:1705"
      - "1704:1704"
    volumes:
      - "snap:/snap"
  playlists:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./manage.py playlists
    depends_on:
      - redis
      - postgres
      - daphne
    volumes:
      - "/srv/nimopidy/:/srv/nimopidy"
      - "./nimopidy:/app/nimopidy"
      - "./musicapp:/app/musicapp"
    env_file:
      - .env
