version: '3'

volumes:
  snap:

services:
  redis:
    image: redis
    restart: unless-stopped
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - "/srv/nimopidy/postgres:/var/lib/postgresql/data"
    env_file:
      - .env
  daphne:
    build: .
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - redis
      - postgres
    command: daphne -b 0.0.0.0 nimopidy.asgi:channel_layer
    env_file:
      - .env
  worker:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - snapserver
    command: ./manage.py runworker
    volumes:
      - "/srv/nimopidy/nimopidy:/srv/nimopidy"
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "7000:8000"
    volumes:
      - "/srv/nimopidy/nimopidy:/srv/nimopidy"
    env_file:
      - .env
  icecast:
    build:
      context: .
      dockerfile: Dockerfile.icecast
    ports:
      - 7001:8000
    env_file:
      - .env
  mopidy:
    build:
      context: .
      dockerfile: Dockerfile.mopidy
    restart: unless-stopped
    ports:
      - "6600:6600"
      - "6680:6680"
    depends_on:
      - worker
      - icecast
      - snapserver
    volumes:
      - "snap:/snap"
  snapserver:
    build:
      context: .
      dockerfile: Dockerfile.snapserver
    ports:
      - "1704:1704"
      - "1705:1705"
    volumes:
      - "snap:/snap"
