# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200, unique=True)),
                ('date', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Playlist')),
            ],
            options={
                'ordering': ('playlist', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200, unique=True)),
                ('date', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lyrics', models.TextField(default=None, null=True)),
                ('length', models.PositiveIntegerField(null=True)),
                ('disc_no', models.PositiveSmallIntegerField(default=0)),
                ('track_no', models.PositiveSmallIntegerField(default=0)),
                ('playcount', models.PositiveIntegerField(default=0)),
                ('last_play', models.DateTimeField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicapp.Album')),
                ('artists', models.ManyToManyField(blank=True, to='musicapp.Artist')),
            ],
            options={
                'ordering': ['date', 'album__name', 'disc_no', 'track_no', 'name'],
            },
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Track'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, to='musicapp.Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together=set([('playlist', 'number')]),
        ),
    ]
