# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('name',)},
        ),
    ]
