# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='last_play',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='playcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
